image: ruby:3.0

before_script:
  - gem install bundler
  - bundle install

pages:
  script:
    - bundle exec jekyll build -d public
  artifacts:
    paths:
      - public
  only:
    - master

stages:
- test
sast:
  stage: test
include:
- template: Security/SAST.gitlab-ci.yml
