# =========================
# 3 Cucharadas — Jekyll 4.x (build local) + Minimal Mistakes (gem)
# =========================

# Tema (gem-based). NO usar remote_theme en build local con gemas.
theme: "minimal-mistakes-jekyll"
minimal_mistakes_skin: "dirt"  # "air","aqua","contrast","dark","dirt","neon","mint","plum","sunrise"

# Site Settings
locale        : "es-CL"
title         : "3 Cucharadas"
title_separator: "-"
subtitle      : "Explorando curiosidades"
name          : &name "Cristián Labra"
description   : &description "Explorando curiosidades"

# Producción (tu hosting actual)
url           : "https://tatanlabra.gitlab.io"
baseurl       : "/3cucharadas"
repository    : "tatanlabra/3cucharadas"

teaser        : "/assets/images/unsplash-image-5.jpg"
logo          : "/assets/images/3cucharadas-logo.png"
masthead_title: "3 Cucharadas ... "
words_per_minute: 200
enable_copy_code_button: true

timezone      : "America/Santiago"   # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
lang          : es

# Comentarios
comments:
  provider: "disqus"

disqus:
  shortname: "Blas_Radomiro"

# Búsqueda (Lunr por defecto en Minimal Mistakes)
search: true
search_full_content: true
# (sin search_provider => Lunr)

# Feed Atom
atom_feed:
  path: /feed.xml

# SEO
google_site_verification: "UQj93ERU9zgECodaaXgVpkjrFn9UrDMEzVamacSoQ8Y"
og_image: "/assets/images/3cucharadas-logo.png"

# Social
twitter:
  username: &twitter "tatanlabra"
facebook:
  username: &facebook "cristianlabra"
social:
  type: "Person"
  name: *name
  links:
    - "https://x.com/tatanlabra"
    - "https://www.facebook.com/cristianlabra"
    - "https://github.com/tatanlabra"
    - "https://gitlab.com/tatanlabra"
    - "https://instagram.com/tatanlabra"

# Analytics (GA4)
analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-P32SL4X2E5"
    anonymize_ip: true

cv_path: /assets/cv/cv_clabraol_2024.pdf

# Autor
author:
  name   : *name
  avatar : "/assets/images/clabra2024.jpg"
  bio    : *description
  location: "Santiago, Chile"
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"      # usar 'fa-linkedin' (FA5); 'fa-linkedin-in' también sirve
      url: "https://www.linkedin.com/in/cristianlabra/"
    # - label: "GitLab"
    #   icon: "fab fa-fw fa-gitlab"
    #   url: "https://gitlab.com/tatanlabra"
    # - label: "GitHub"
    #   icon: "fab fa-fw fa-github"
    #   url: "https://github.com/tatanlabra"      
    # - label: "X (Twitter)"
    #   icon: "fab fa-fw fa-twitter"       # en FA5 NO existe 'fa-x-twitter'
    #   url: "https://x.com/tatanlabra"
    # - label: "Mastodon"
    #   icon: "fab fa-fw fa-mastodon"
    #   url: "https://mastodon.social/@asiole"
    # - label: "Bluesky"
    #   icon: "fa-brands fa-bluesky"         # FA5 no trae 'fa-bluesky'; usamos un fallback neutro
    #   url: "https://bsky.app/profile/labra.bsky.social"
    - label: "CV"
      icon: "fas fa-fw fa-file-pdf"
      url: "/3cucharadas/assets/cv/cv_clabraol_2024.pdf"  # ver nota abajo

# Footer
footer:
  links:
    - label: "X"
      icon: "fab fa-fw fa-x-twitter"
      url: "https://x.com/tatanlabra"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/tatanlabra"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/tatanlabra"

# Lectura/Exclusiones
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
keep_files:
  - .git
  - .svn

encoding    : "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversión/Markdown
markdown    : kramdown
highlighter : rouge
lsi         : false
excerpt_separator: "\n\n"
incremental : false

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Colecciones (ejemplos desactivados)
collections:
  # docs:
  #   output: false
  #   permalink: /:collection/:path/

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      toc: true
      toc_sticky: true
      comments: true     # actívalo por post cuando configures el provider
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Salida/URLs
permalink    : /:categories/:title/
paginate     : 5
paginate_path: /page:num/

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-seo-tag

# Archivos (categorías/tags por páginas dedicadas)
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# Compresión HTML (opcional; inofensivo si no usas layout específico)
compress_html:
  clippings: all
  ignore:
    envs: development
